version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/home/app/backend
    ports:
      - "8001:8000"

  bot:
    build:
      context: tg_bot
      dockerfile: Dockerfile
    env_file:
      - tg_bot/.env
    depends_on:
      - backend

  db:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres_data_prod:
