# Generated by Django 5.0.6 on 2024-06-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompaniesPayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(
                        default=None,
                        max_length=512,
                        null=True,
                        verbose_name="Название компании плательщика",
                    ),
                ),
                (
                    "company_inn",
                    models.CharField(
                        max_length=10, verbose_name="ИНН плательщика 10 цифр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания плательщик",
                "verbose_name_plural": "Компании плательщики",
            },
        ),
        migrations.CreateModel(
            name="CompaniesRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(
                        default=None,
                        max_length=512,
                        null=True,
                        verbose_name="Название компании получателя",
                    ),
                ),
                (
                    "company_inn",
                    models.CharField(
                        max_length=12, verbose_name="ИНН получателя 12 цифр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания получатель",
                "verbose_name_plural": "Компании получатели",
            },
        ),
        migrations.CreateModel(
            name="TelegamUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tg_username",
                    models.CharField(
                        max_length=512,
                        unique=True,
                        verbose_name="Никнеим автора заявки в tg",
                    ),
                ),
                (
                    "tg_user_id",
                    models.IntegerField(
                        unique=True, verbose_name="ID автора заявки в tg"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=512,
                        null=True,
                        verbose_name="Имя автора заявки в tg",
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=512,
                        null=True,
                        verbose_name="Фамилия автора заявки в tg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор заявки в tg",
                "verbose_name_plural": "Авторы заявкок в tg",
            },
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cost", models.IntegerField(verbose_name="Сумма заявки")),
                (
                    "target_date",
                    models.DateTimeField(verbose_name="Дата исполнения заявки"),
                ),
                (
                    "inn_payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications_as_payer",
                        to="applications.companiespayer",
                        verbose_name="ИНН получателя",
                    ),
                ),
                (
                    "inn_recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications_as_recipient",
                        to="applications.companiesrecipient",
                        verbose_name="ИНН плательщика",
                    ),
                ),
                (
                    "tg_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.telegamusers",
                        verbose_name="Автор заявки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
