# Generated by Django 5.0.6 on 2024-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companiespayer",
            name="company_inn",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="ИНН плательщика 10 цифр"
            ),
        ),
        migrations.AlterField(
            model_name="companiesrecipient",
            name="company_inn",
            field=models.CharField(
                max_length=12, unique=True, verbose_name="ИНН получателя 12 цифр"
            ),
        ),
    ]
