# Generated by Django 5.0.6 on 2024-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="target_date",
            field=models.DateField(verbose_name="Дата исполнения заявки"),
        ),
    ]
