# Generated by Django 5.0.6 on 2024-06-12 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_companiespayer_company_inn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companiespayer",
            name="tg_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.telegamusers",
                verbose_name="Владелец компании",
            ),
        ),
        migrations.AddField(
            model_name="companiesrecipient",
            name="tg_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.telegamusers",
                verbose_name="Владелец компании",
            ),
        ),
    ]
