# Generated by Django 5.0.6 on 2024-10-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_telegamusers_tg_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="app_status",
            field=models.CharField(
                choices=[
                    ("Новая", "Новая"),
                    ("В работе", "В работе"),
                    ("Счёт в оплате", "Счёт в оплате"),
                    ("Выполнена", "Выполнена"),
                ],
                default="Новая",
                max_length=200,
                verbose_name="Статус заявки",
            ),
        ),
    ]
