# Generated by Django 5.0.6 on 2024-06-06 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_applications_target_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="cost",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000000),
                ],
                verbose_name="Сумма заявки",
            ),
        ),
    ]
