# Generated by Django 5.0.6 on 2024-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_applications_app_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="app_status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("in_progress", "В работе"),
                    ("completed", "Выполнена"),
                ],
                default="new",
                max_length=200,
                verbose_name="Статус заявки",
            ),
        ),
    ]
