# Generated by Django 5.0.6 on 2024-06-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_companiespayer_tg_user_companiesrecipient_tg_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companiespayer",
            unique_together={("tg_user", "company_inn")},
        ),
        migrations.AlterUniqueTogether(
            name="companiesrecipient",
            unique_together={("tg_user", "company_inn")},
        ),
    ]
