# Generated by Django 5.0.6 on 2024-06-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_companiespayer_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companiespayer",
            old_name="company_inn",
            new_name="company_inn_payer",
        ),
        migrations.RenameField(
            model_name="companiespayer",
            old_name="company_name",
            new_name="company_name_payer",
        ),
        migrations.RenameField(
            model_name="companiesrecipient",
            old_name="company_inn",
            new_name="company_inn_recipient",
        ),
        migrations.RenameField(
            model_name="companiesrecipient",
            old_name="company_name",
            new_name="company_name_recipient",
        ),
        migrations.AlterUniqueTogether(
            name="companiespayer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="companiesrecipient",
            unique_together=set(),
        ),
    ]
