# Generated by Django 5.0.6 on 2024-12-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_usermessagelog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagelog",
            options={
                "verbose_name": "История рассылок",
                "verbose_name_plural": "История рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="messagetemplate",
            options={"verbose_name": "Рассылки", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="telegamusers",
            options={"verbose_name": "Клиенты", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="telegramgroup",
            options={
                "verbose_name": "Группы клиентов",
                "verbose_name_plural": "Группы клиентов",
            },
        ),
    ]
