# Generated by Django 5.0.6 on 2025-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_alter_messagelog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="comment",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Комментарии к заявке"
            ),
        ),
    ]
