# Generated by Django 5.0.6 on 2024-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("tg_user_id", models.CharField(max_length=255)),
                ("app_id", models.CharField(max_length=255)),
                ("json_data", models.TextField()),
                (
                    "dispatch_status",
                    models.CharField(default="received", max_length=50),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
